# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 09:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postss', '0002_contact_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_model',
            old_name='content',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contact_model',
            name='contact_no',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
