# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postss', '0003_auto_20160617_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
